require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/*
    - db/**/*
    - vendor/**/*
  DisplayCopNames: true
Documentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Metrics/BlockLength:
  Max: 150
Metrics/ClassLength:
  Max: 250
Metrics/LineLength:
  Max: 100
RSpec/NestedGroups:
  Max: 5
Style/ClassAndModuleChildren:
  Enabled: false
Style/AsciiComments:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false
Lint/FormatParameterMismatch:
  Enabled: false
