require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.1
  Exclude:
    - bin/*
    - db/**/*
    - vendor/**/*
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/ClassLength:
  Max: 250
RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*
RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*
RSpec/NestedGroups:
  Max: 4
Style/ClassAndModuleChildren:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false

# https://github.com/rubocop-hq/rubocop/issues/7264
Rails/HttpPositionalArguments:
  Exclude:
    - spec/controllers/**/*
